#HIDIVE Downloader NX configuration v3
bin:
  ffmpeg: /usr/bin/ffmpeg
  mkvmerge: /usr/bin/mkvmerge
dir:
  content: /content/drive/Shareddrives/HVEC/HIDIVE/
  trash: ${__dirname}/videos/_trash/
cli:
  releaseGroup: HIDIVE
  # assTitleTag: HIDIVE
  # muxTitleTag: HIDIVE
  fileSuffix: SIZEp
  videoQuality: 1080p
  dubLanguage: jpn
  # mp4mux: false
  # muxSubs: false
  # capsSubs: false
  # assFont: Open Sans Semibold
  # noCleanUp: false
#eof
